// jshint esversion: 9
import React, { useState } from 'react';

import IngredientForm from './IngredientForm';
import Search from './Search';
import IngredientList from './IngredientList';

const Ingredients = () => {
  const [userIngredients, setUserIngredients] = useState([]);

  const removeIngredientHandler = (ingredientId) => {
    setUserIngredients(prevIngredients => {
      return prevIngredients.filter((ingredient) => {
        return ingredient.id !== ingredientId;
      });
    });
  };

  const addIngredientHandler = (ingredient) => {
    // this is where we want to send our data to and you got to know what have fetched by default will send a get request a firebase once a post request though if we want to store data hence we pass a second argument to fetch and that's an object that allows us to configure this request in on this object we can set the method property to post default the set then you never need to set that but we want to set this to post you then also can add a body property to define what you want to send and that has to be json data which means you can use json which is another thing built into the browser it's a class in the end built in to browsers which has a stringify method. This will take a javascript object or array and convert it into valid json format
    fetch('https://react-hooks-a1e9b.firebaseio.com/ingredients.json', {
      method: 'POST',
      body: JSON.stringify(ingredient),
      headers: {'Content-Type': 'application/json'}
    }).then(response => {
      // this response actually will get some data back from firebase which contains that automatically generated id response itself however is a more complex object we're interested in the body of that responds and you get that by calling the Jason method there. This will extract the body and convert it from Jason to normal javascript code however this also returns a promise so we'll actually return response Jason here. and move this code into a neighbor then block which a change here which will be my my body
      return response.json();
    }).then(responseData => {
      // I get responseData or body in this function here which I passed the second then block which executes once this body has been parsed and now response data will be an object which has a name property which contains does automatically generated id, that's just how firebase works.
      setUserIngredients(prevIngredients => [
        //  here the idea will be to call set user ingredients and now important we'll need to update the existing list of ingredients and add a new one. Now that means we depend on the current state and they offer it's best if we use the functional forum where we're guaranteed to get the latest state. So we get our previous ingredients here our older array basically the current state. This is a spread operator taking all elements of our old array and adding them as elements to this new Array which I'm constructing with the square brackets. And then to add one new element here and that's the ingredient we're getting now important ingredient we're getting from the ingredient form we'll have a title and an amount.
        ...prevIngredients, 
        // we can access code name here has nothing to do with react or with the fetch API that's just firebase it returns some data which the end is a javascript object which has a name property and that name property will have that unique I.D. which was generated by firebase.
        {id: responseData.name,
          // we can again use to spread operator on ingredient now. So on this argument we're getting because this argument will be an object let's say the spread operator then takes all key value pairs from that object and adds key and value pairs to this new object. So now we're adding a new object with an I.D. title in amount to our list of ingredients here.
          ...ingredient}
      ]);
    })
  };
  return (
    <div className="App">
      <IngredientForm onAddIngredient={addIngredientHandler}/>
      <section>
        <Search />
        <IngredientList 
          ingredients={userIngredients}
          onRemoveItem={removeIngredientHandler} />
      </section>
    </div>
  );
}

export default Ingredients;
